import type { Metadata } from "next";
// Commented out to fix build error due to Google Fonts fetch failure
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {TRPCReactProvider} from "@/trpc/client"

// Commented out font definitions to prevent fetching issues
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "meet-me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
    <html lang="en">
      <body
        // Commented out font variables to fix build error
        className={`antialiased min-h-screen flex flex-col`}
      >
        <main className="flex-1">
          {children}
        </main>
        <footer className="text-center text-sm text-gray-500 py-4 border-t">
          Version 0.1.0 - Beta Version - Soumen Manik Copyright
        </footer>
      </body>
    </html>
    </TRPCReactProvider>
  );
}
